[phases.setup]
nixPkgs = ["python311", "gcc", "libomp"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install --no-cache-dir -r backend/requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && python main.py"
